project_id = "ducfdifmzdcmahfrijwj"

[functions.screen-resume]
verify_jwt = false

[functions.generate-interview-question]
verify_jwt = false

[functions.evaluate-interview]
verify_jwt = false

[functions.generate-company-question]
verify_jwt = false

[functions.evaluate-company-prep]
verify_jwt = false
